import { useMemo } from 'react'
import { useSearchParams, Link } from 'react-router-dom'
import { CheckCircle, XCircle, ShieldCheck } from 'lucide-react'
import logoSrc from '@/assets/gaposa-logo.png'

function decode(str) {
  try {
    return JSON.parse(decodeURIComponent(
      Array.from(atob(str)).map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)).join('')
    ))
  } catch { return null }
}

export default function VerifyPage() {
  const [params] = useSearchParams()
  const raw  = params.get('c')
  const data = useMemo(() => (raw ? decode(raw) : null), [raw])

  const overall = useMemo(() => {
    if (!data?.cs?.length) return 0
    const totalPresent = data.cs.reduce((s, c) => s + (c.p || 0), 0)
    const totalClasses = data.cs.reduce((s, c) => s + (c.t || 0), 0)
    return totalClasses > 0 ? Math.round(totalPresent / totalClasses * 100) : 0
  }, [data])

  const card = { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 16, padding: '1.25rem 1.5rem', boxShadow: '0 2px 12px rgba(31,111,95,0.07)' }

  return (
    <div style={{ minHeight: '100vh', background: '#f7fffe', fontFamily: "'Albert Sans', system-ui, sans-serif", padding: '1.5rem 1rem' }}>
      <div style={{ maxWidth: 560, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1rem' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem', padding: '0.85rem 1.25rem', background: '#fff', borderRadius: 16, border: '1px solid #e2e8f0', boxShadow: '0 2px 12px rgba(31,111,95,0.07)' }}>
          <img src={logoSrc} alt="Logo" style={{ width: 44, height: 44, objectFit: 'contain', flexShrink: 0 }} />
          <div>
            <p style={{ margin: 0, fontSize: '0.75rem', fontWeight: 900, color: '#1F6F5F', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Gateway ICT Polytechnic</p>
            <p style={{ margin: '1px 0 0', fontSize: '0.65rem', color: '#94a3b8', fontWeight: 600 }}>EEE FACE-ID — Certificate Verification</p>
          </div>
          <div style={{ marginLeft: 'auto' }}>
            <ShieldCheck size={22} color="#2FA084" />
          </div>
        </div>

        {!data ? (
          /* Invalid QR */
          <div style={{ ...card, textAlign: 'center', padding: '3rem 2rem' }}>
            <XCircle size={48} color="#dc2626" style={{ margin: '0 auto 1rem' }} />
            <p style={{ margin: 0, fontWeight: 800, fontSize: '1rem', color: '#1e293b' }}>Invalid Certificate</p>
            <p style={{ margin: '0.4rem 0 0', fontSize: '0.82rem', color: '#6b7280', lineHeight: 1.55 }}>
              This QR code is not a valid EEE FACE-ID certificate. It may be tampered with or expired.
            </p>
            <p style={{ margin: '0.75rem 0 0', fontSize: '0.72rem', color: '#94a3b8' }}>Contact the Department for verification.</p>
          </div>
        ) : (
          <>
            {/* Verified stamp */}
            <div style={{ background: 'linear-gradient(135deg, #1F6F5F 0%, #2FA084 100%)', borderRadius: 16, padding: '1.25rem 1.5rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <CheckCircle size={26} color="#fff" strokeWidth={2.5} />
              </div>
              <div>
                <p style={{ margin: 0, fontSize: '1rem', fontWeight: 900, color: '#fff' }}>Certificate Verified</p>
                <p style={{ margin: '2px 0 0', fontSize: '0.72rem', color: 'rgba(255,255,255,0.7)' }}>
                  Generated by EEE FACE-ID Attendance System · {data.dt || '—'}
                </p>
              </div>
            </div>

            {/* Student details */}
            <div style={card}>
              <p style={{ margin: '0 0 0.85rem', fontSize: '0.65rem', fontWeight: 800, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Student Information</p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.85rem' }}>
                {[
                  ['Full Name',     data.n  || '—'],
                  ['Matric Number', data.m  || '—'],
                  ['Level',         data.lv || '—'],
                  ['Option',        data.op || '—'],
                  ['Session',       data.ss || '—'],
                  ['Semester',      data.sm || '—'],
                ].map(([label, value]) => (
                  <div key={label}>
                    <p style={{ margin: 0, fontSize: '0.62rem', color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em' }}>{label}</p>
                    <p style={{ margin: '2px 0 0', fontSize: '0.85rem', fontWeight: 800, color: '#1e293b', wordBreak: 'break-word' }}>{value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Course attendance */}
            <div style={{ ...card, padding: 0, overflow: 'hidden' }}>
              <div style={{ padding: '0.85rem 1.25rem', borderBottom: '1px solid #f1f5f9' }}>
                <p style={{ margin: 0, fontSize: '0.78rem', fontWeight: 800, color: '#0f172a' }}>Course Attendance Record</p>
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ background: '#f8fafc' }}>
                    {['Course', 'Present', 'Total', 'Rate'].map(h => (
                      <th key={h} style={{ padding: '0.55rem 1rem', textAlign: h === 'Course' ? 'left' : 'center', fontSize: '0.62rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.06em', borderBottom: '1px solid #f1f5f9' }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {(data.cs || []).map((c, i) => {
                    const pct = c.t > 0 ? Math.round(c.p / c.t * 100) : 0
                    return (
                      <tr key={i} style={{ borderBottom: '1px solid #f8fafc' }}>
                        <td style={{ padding: '0.6rem 1rem', fontSize: '0.82rem', fontWeight: 700, color: '#1e293b' }}>{c.c}</td>
                        <td style={{ padding: '0.6rem 1rem', textAlign: 'center', fontSize: '0.82rem', color: '#16a34a', fontWeight: 600 }}>{c.p}</td>
                        <td style={{ padding: '0.6rem 1rem', textAlign: 'center', fontSize: '0.82rem', color: '#64748b' }}>{c.t}</td>
                        <td style={{ padding: '0.6rem 1rem', textAlign: 'center', fontSize: '0.85rem', fontWeight: 800, color: pct >= 75 ? '#d97706' : '#dc2626' }}>{c.t > 0 ? `${pct}%` : '—'}</td>
                      </tr>
                    )
                  })}
                  <tr style={{ background: '#f8fafc', borderTop: '2px solid #e2e8f0' }}>
                    <td style={{ padding: '0.65rem 1rem', fontSize: '0.78rem', fontWeight: 800, color: '#1e293b' }}>Overall</td>
                    <td style={{ padding: '0.65rem 1rem', textAlign: 'center', fontSize: '0.78rem', fontWeight: 700, color: '#16a34a' }}>{(data.cs || []).reduce((s, c) => s + (c.p || 0), 0)}</td>
                    <td style={{ padding: '0.65rem 1rem', textAlign: 'center', fontSize: '0.78rem', color: '#64748b' }}>{(data.cs || []).reduce((s, c) => s + (c.t || 0), 0)}</td>
                    <td style={{ padding: '0.65rem 1rem', textAlign: 'center', fontSize: '0.85rem', fontWeight: 900, color: overall >= 75 ? '#d97706' : '#dc2626' }}>{overall}%</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Notice */}
            <div style={{ background: 'rgba(47,160,132,0.06)', border: '1px solid rgba(47,160,132,0.18)', borderRadius: 12, padding: '0.85rem 1.1rem' }}>
              <p style={{ margin: 0, fontSize: '0.72rem', color: '#1F6F5F', fontWeight: 600, lineHeight: 1.6 }}>
                This certificate was generated from the EEE FACE-ID biometric attendance system at Gateway ICT Polytechnic. The data above reflects the student's recorded attendance at the time of generation. For discrepancies, contact the Department of Electrical/Electronics Engineering.
              </p>
            </div>

            <Link to="/" style={{ textAlign: 'center', fontSize: '0.72rem', color: '#94a3b8', display: 'block', paddingBottom: '1rem' }}>
              gaposa-eee-face-id-attendance-syste.vercel.app
            </Link>
          </>
        )}
      </div>
    </div>
  )
}
